from .ComplEx import ComplEx
from .DistMult import DistMult
from .HolE import HolE
from .RESCAL import RESCAL
from .TransD import TransD
from .TransE import TransE
from .TransH import TransH
from .TransR import TransR
from .Analogy import Analogy
